lib/followsoccer_web/router.ex
defmodule FollowsoccerWeb.Router do
  use FollowsoccerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :get_current_user
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  def get_current_user(conn, _params) do
    # TODO: Move this function out of the router module.
    user_id = get_session(conn, :user_id)
    user = Followsoccer.Accounts.get_user(user_id || -1)
    IO.inspect "in get cur user"
    IO.inspect user
    assign(conn, :current_user, user)
  end

  scope "/", FollowsoccerWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    post "/session", SessionController, :create
    delete "/session", SessionController, :delete
    resources "/users", UserController
    get "/feed", PageController, :feed
    get "/soccerteams/:soccerteams", PageController, :feed
  end

  # Other scopes may use custom stacks.
  scope "/api/v1", FollowsoccerWeb do
    pipe_through :api
    resources "/users", UserController, except: [:new, :edit]
    resources "/leagues", LeagueController, except: [:new, :edit]
    resources "/follows", FollowController, except: [:new, :edit]
  end
end

lib/followsoccer_web/templates/page/feed.html.eex
<%= if @current_user do %>
<script>
  var user = {};
  user["name"] = "<%= @current_user.name %>";
  user["email"] = "<%= @current_user.email %>";
  user["id"] = "<%= @current_user.id %>"
  window.user = user;
  //console.log("email: "+window.user.id);
  var listOfFollowedTeams = [];
  <%= if Enum.count(@myTeams)!=0 do %>
  <%= Enum.map @myTeams, fn team -> %>
  var team = {};
  team['tname'] = "<%= team.tname %>";
  team['tcode'] = "<%= team.tcode %>";
  team['subscribe'] = "<%= team.subscribe %>";
  team['id'] = "<%= team.id %>"
  listOfFollowedTeams.push(team);
  <% end %>
  <% end %>
  //console.log(listOfFollowedTeams);
  window.followedTeams = listOfFollowedTeams;
</script>

  <div id="root">
    <p>React app loading</p>
  </div>
<% end %>

lib/followsoccer_web/templates/page/index.html.eex
<body id="bg-img">
<h1>Log In to Follow Soccer</h1>
<hr />
   <!-- session_path(@conn, :create) -->
   <%= form_tag("/session", method: :post) do %>
     <div class="form-group">
       Enter your Email:
       <br/>
       <input type="email"  name="email" placeholder="user@example.com" class= "form-control" required>
     </div>
     <br/>
     <div class="form-group">
       Password:
       <br/>
       <input type="password" name="password" class= "form-control" required>
     </div>

     <br/>
     <!-- passwords come later -->
     <div class="form-group">
       <button class="btn btn-primary">Log in</button>
       <br/>
       <br/>
       New user ? <%= link "Register here", to: user_path(@conn, :new) %>
       <br/>
     </div>
   <% end %>
</body>